name: Test and Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.7"

      - name: Run tests
        run: go test -json ./... > /tmp/TestResults.json

      - name: Upload Go test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: TestResults.json
          path: /tmp/TestResults.json

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.7"

      - name: Get GOOS and GOARCH
        id: get-go-env
        run: |
          echo "GOOS=$(go env GOOS)" >> "$GITHUB_OUTPUT"
          echo "GOARCH=$(go env GOARCH)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Build
        run: go build -o cloud-verify-${{ env.GOOS }}-${{ env.GOARCH }}
        env:
          GOOS: ${{ steps.get-go-env.outputs.GOOS }}
          GOARCH: ${{ steps.get-go-env.outputs.GOARCH }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: cloud-verify-${{ env.GOOS }}-${{ env.GOARCH }}
          path: cloud-verify-${{ env.GOOS }}-${{ env.GOARCH }}
        env:
          GOOS: ${{ steps.get-go-env.outputs.GOOS }}
          GOARCH: ${{ steps.get-go-env.outputs.GOARCH }}

  hash:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Move artifacts
        run: find artifacts -type f -exec mv "{}" . \;

      - name: Get Hashes
        run: sha256sum -b cloud-verify-* > SHA256SUMS

      - name: Upload SHA256SUMS file
        uses: actions/upload-artifact@v3
        with:
          name: SHA256SUMS
          path: SHA256SUMS