name: Versioning

on:
  push:
    branches:
      - main

permissions:
  contents: write-all

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1
        with:
          main_branch: main
          create_tag: true
          tag_prefix: "v"
      - name: Invoke goreleaser
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: goreleaser.yml
